# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            Jeekons
author:           Roney Stones
email:            roneylacerda@gmail.com
description:      Start project with Jekyll, Tachyons and Gulp
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-xxxxxxxx-x

# Assets
sass:
  sass_dir:       _scss
  style:          :compressed

# Build settings
markdown:         kramdown

plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
